### ISSUE TITLE
MC crashes

### ISSUE THREAD

**Issue by voidrinix** [opekope2/OptiGUI-Legacy#16]
Hello. Mod loader is Quilt 0.17.4
![image](https://user-images.githubusercontent.com/73175330/190899702-65ef2b45-a648-424c-9380-ab44aa048496.png)

Here is the crash log 
[crash-2022-09-18_14.25.18-client.txt](https://github.com/opekope2/OptiGUI/files/9593845/crash-2022-09-18_14.25.18-client.txt)

**Comment by opekope2** [comment]
Does it crash after you leave a world/server?

**Comment by voidrinix** [comment]
> Does it crash after you leave a world/server?

yes, I left from the server to the main menu, and after I pressed "Multiplayer" button I saw this

**Comment by opekope2** [comment]
Then the issue is that when I added caching to improve performance, I forgot to invalidate the cache. The cache then tried to access the world, which is not loaded. I'll fix it today.

**Comment by voidrinix** [comment]
thx)

**Comment by opekope2** [comment]
I'll close the issue as soon as I fix the bug.
