### ISSUE TITLE
problems again

### ISSUE THREAD

**Issue by voidrinix** [opekope2/OptiGUI-Legacy#17]
Hello. I'm sorry for annoying. I installed the last version (1.1.3) but my mc client keeps crashing after leaving the server.
What needs to be done to reproduce:
1. Open minecraft
2. join server
3. leave it
4. get a crash notification
 Here is the crash log
[crash-2022-09-18_19.08.47-client.txt](https://github.com/opekope2/OptiGUI/files/9594388/crash-2022-09-18_19.08.47-client.txt)

**Comment by opekope2** [comment]
I optimized and added checks to the crashing code, so it *really shouldn't* crash starting at v1.1.4.
It never crashed with Fabric on my computer.
