### ISSUE TITLE
Resource pack Loading Failure v1.1.5

### ISSUE THREAD

**Issue by JustAHuman-xD** [opekope2/OptiGUI-Legacy#22]
I'm getting this error whenever I try to load my custom gui's
[OptiGuiFailure.txt](https://github.com/opekope2/OptiGUI/files/9649803/OptiGuiFailure.txt)

**Comment by JustAHuman-xD** [comment]
It worked fine until the later updates, don't know what to do

**Comment by opekope2** [comment]
Can you send the resource pack so I can look into it? I suspect that something is wrong with it.

**Comment by BossCreeper81** [comment]
For me it's caused by Colourful Containers, as well as the Addon
(havent tested wether or not it's a mod conflict yet)

The Resource Pack works fine on 1.1.4

1.19.2 Quilt

**Comment by opekope2** [comment]
Can you send the log?

**Comment by MissGamerz** [comment]
this seems to be a namespacing problem on the mods part 
[04:43:56] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine\gui\container\chests/chest


not there is no weird characters like whitespaces or anything in the texture name

**Comment by opekope2** [comment]
One cause can be that there are backslashes (`\`) in the .properties file instead of forward slashed (`/`).
Another issue could be the windows path separator, but I think Minecraft handles that. "Write once, run everywhere". Only tested it on Arch Linux.
Making the mod resistant against malformed resource packs is on my TODO list.

**Comment by opekope2** [comment]
Looked at the updated code and it's probably `java.io.File` adding backslashes instead of forward ones on Windows.

**Comment by MissGamerz** [comment]
container=chest
**texture=chest**
ender=false
christmas=false

**Comment by opekope2** [comment]
There's nothing wrong with the resource packs, v1.1.5 is broken on Windows. I'll fix it in v1.1.6 when I have time, use v1.1.4 till then.
The other 2 issues probably will have to wait till v1.1.7.
