### ISSUE TITLE
Mark 1.19.3 as compatible on CurseForge and Modrinth

### ISSUE THREAD

**Issue by RoonMoonlight** [opekope2/OptiGUI-Legacy#26]
Title says it all

**Comment by opekope2** [comment]
I'll test it first to make sure it compiles (meaning no breaking change was introduced to Minecraft source code (a breaking change is why 1.18-1.18.1 would require a different build from 1.18.2)), then I'll mark it as compatible. I'll have some time to do it next week (probably).

**Comment by opekope2** [comment]
The current 1.19 build is **NOT** compatible with 1.19.3, because the registry API got changed.

**Comment by opekope2** [comment]
I updated the project to 1.19.3, and will release it soon (as soon as the GitHub build succeeds).
This update doesn't include any new feature or improvement, just a build for 1.19.3, so the version will not be incremented.

**Comment by opekope2** [comment]
The update is live on all 3 official release channels (GitHub releases, Modrinth, and CurseForge)
