### ISSUE TITLE
Added barrel support

### ISSUE THREAD

**Issue by raspberrygitq** [opekope2/OptiGUI-Legacy#28]
When I loaded a resource pack with a custom GUI just barrels is not supported.

**Comment by opekope2** [comment]
The barrel feature is not supported by OptiFine, it is an extension feature by OptiGUI. There is a resource pack mentioned in README. Can you send the lint to it, so I can examine what might be the problem?

**Comment by opekope2** [comment]
If you still have this issue with the new versions, please create a new issue at [opekope2/OptiGUI](https://github.com/opekope2/OptiGUI) with more details.
