### ISSUE TITLE
Question does this mod have support for the color.properties file?

### ISSUE THREAD

**Issue by dewwdrp** [opekope2/OptiGUI-Legacy#5]
Well, exactly as the title says, is there support for the color.properties file? Specifically the line that changes the xp text color? Also does the path for the file have to be different than how it is for optifine? I'm asking because I have a personal edit of the hotbar and it uses the color.properties file to change the xp text color. I've installed the mod and it doesn't seem to support it but I thought I'd ask just in case I needed to change something around and missed it. Obviously I can live without it seeing as I've switched to fabric and sodium/iris/other mods, but I would really love to have that feature back if it's supported/possible.

By the way, thank you for sharing your hard work with everyone, I'm not a modder so I can't imagine the work you put into this, and I wanted to say thank you. :)

**Comment by opekope2** [comment]
No, this mod does not support `color.properties`.

1. The mod only replaces GUI textures which are located in `optifine/gui/container/` folder ([see implementation](https://github.com/opekope2/OptiGUI/blob/6f92cfab36ff1abb2fdbbf2065ee4aabaa25b3db/src/main/java/opekope2/optigui/optifinecompat/OptifineResourceLoader.java#L23)).
2. `color.properties` is located in `optifine/` folder.
3. `color.properties` does not replace a texture with another, it works differently.
4. [Colormatic](https://github.com/kvverti/colormatic) supports this feature.

As of now, I am not planning to implement  `color.properties` support.

**Comment by dewwdrp** [comment]
Ah, okay. Sorry I'm still learning and I didn't realize your mod was supporting textures only, my mistake! At any rate, thank you for the reply and letting me know about colormatic. Also again, thank you for sharing your hard work. ^^
