### ISSUE TITLE
Toggle outside-Curseforge distribution

### ISSUE THREAD

**Issue by Madis0** [opekope2/OptiGUI-Legacy#6]
Could you enable this toggle?

![](https://i.ibb.co/n3L95Hm/Screenshot-20220509-192849-Berry-Browser.png)

That means the users who use launchers like MultiMC or GDLauncher can continue to download your mod. Otherwise when they download a modpack, they'll get everything except your mod and are prompted to download it manually.

**Comment by opekope2** [comment]
Sure thing
