### ISSUE TITLE
Issue when reloading, Caused by using name parameter

### ISSUE THREAD

**Issue by JustAHuman-xD** [opekope2/OptiGUI-Legacy#7]
Problem: When using the name= parameter for a gui doing F3+T or reloading resource packs any other way fails.
If i remove the properties file that is using the name parameter it works normally, this happens with a properties file of a chest with the only thing added being the names property. I thought it might have been the iregex: but removing that made no change.

This is what the properties file contains:
container=chest
texture=chest		
ender=false
name=iregex:backpack

**Comment by opekope2** [comment]
#8 fixes the crash, but it disables name matching for block entities, as they somehow lose custom names after a world reload. If a solution is found to obtain it in some other way (because they are still displayed in the GUI), I will re-enable it. Until then, I'll leave this issue open.

**Comment by JustAHuman-xD** [comment]
Is this true for multiplayer servers? I found this by trying to make custom guis for things like /ec and backpacks which open a chest based gui

**Comment by opekope2** [comment]
I'll test it later, but I suspect that after a server restart, the same thing would happen.
